# Generated by Django 5.2.7 on 2025-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealid', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.JSONField()),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField()),
                ('image', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
