# Generated by Django 5.2.7 on 2025-11-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_user_added',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(choices=[('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('oz', 'ounce'), ('lb', 'pound'), ('ml', 'milliliter'), ('l', 'liter'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('cup', 'cup'), ('pinch', 'pinch'), ('dash', 'dash'), ('pcs', 'pieces'), ('packet', 'packet'), ('can', 'can'), ('bottle', 'bottle')], max_length=10)),
                ('shop', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
