# Generated by Django 5.2.7 on 2025-11-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meal_is_user_added_grocerylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='core.meal'),
        ),
    ]
