# Generated by Django 5.2.7 on 2025-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grocerylist_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='meal',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='meal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
