# Generated by Django 5.2.7 on 2025-11-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_grocerylist_meal_grocerylist_meal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='ingredient_name',
        ),
    ]
