# Generated by Django 5.2.7 on 2025-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_grocerylist_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='meal_name',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='ingredient_name',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
