# Generated by Django 5.2.7 on 2025-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_grocerylist_meal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='ingredient_name',
            field=models.CharField(max_length=255),
        ),
    ]
