# Generated by Django 5.2.7 on 2025-12-12 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipeview'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('mealid', 'user')},
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'is_user_added', '-created_at'], name='core_meal_user_id_c992cc_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['is_public', '-created_at'], name='core_meal_is_publ_1574a6_idx'),
        ),
    ]
